package forms.dialogs;

import filters.PhoneFilter;
import javax.swing.text.PlainDocument;

public class ClientDialog extends javax.swing.JDialog {

    public ClientDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        PlainDocument doc = (PlainDocument) PhoneField.getDocument();
        doc.setDocumentFilter(new PhoneFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PassportField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SurnameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PatronimycField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BirthField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PhoneField = new javax.swing.JTextField();
        EditOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Клиент");

        DialogTitle.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        DialogTitle.setForeground(new java.awt.Color(0, 156, 190));
        DialogTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DialogTitle.setText("Редактировать");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Номер паспорта");

        PassportField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        PassportField.setForeground(new java.awt.Color(30, 30, 30));
        PassportField.setDisabledTextColor(new java.awt.Color(50, 50, 50));
        PassportField.setEnabled(false);
        PassportField.setSelectionColor(new java.awt.Color(0, 156, 190));

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Фамилия");

        SurnameField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        SurnameField.setForeground(new java.awt.Color(30, 30, 30));
        SurnameField.setSelectionColor(new java.awt.Color(0, 156, 190));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Имя");

        NameField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        NameField.setForeground(new java.awt.Color(30, 30, 30));
        NameField.setSelectionColor(new java.awt.Color(0, 156, 190));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Отчество");

        PatronimycField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        PatronimycField.setForeground(new java.awt.Color(30, 30, 30));
        PatronimycField.setSelectionColor(new java.awt.Color(0, 156, 190));

        jLabel6.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Дата рождения");

        BirthField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        BirthField.setForeground(new java.awt.Color(30, 30, 30));
        BirthField.setDisabledTextColor(new java.awt.Color(50, 50, 50));
        BirthField.setEnabled(false);
        BirthField.setSelectionColor(new java.awt.Color(0, 156, 190));

        jLabel7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Номер телефона");

        PhoneField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        PhoneField.setForeground(new java.awt.Color(30, 30, 30));
        PhoneField.setSelectionColor(new java.awt.Color(0, 156, 190));

        EditOK.setBackground(new java.awt.Color(0, 156, 190));
        EditOK.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        EditOK.setForeground(new java.awt.Color(255, 255, 255));
        EditOK.setText("ОК");
        EditOK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(15, 212, 255), new java.awt.Color(0, 175, 214), new java.awt.Color(0, 58, 71), new java.awt.Color(0, 112, 137)));
        EditOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditOKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("+375");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatronimycField)
                                    .addComponent(BirthField)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PassportField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(SurnameField)
                                    .addComponent(NameField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(EditOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addComponent(DialogTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(DialogTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PassportField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatronimycField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(EditOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_EditOKActionPerformed

    public void setDialogTitle(String title) {
        DialogTitle.setText(title);
    }
    
    public void setPassport(String passport) {
        PassportField.setText(passport);
    }

    public void setSurname(String surname) {
        SurnameField.setText(surname);
    }

    public void setName(String name) {
        NameField.setText(name);
    }

    public void setPatronimyc(String patronimyc) {
        PatronimycField.setText(patronimyc);
    }

    public void setBirth(String birth) {
        BirthField.setText(birth);
    }

    public void setPhone(String phone) {
        PhoneField.setText(phone);
    }

    public String getPassport() {
        return PassportField.getText();
    }

    public String getSurname() {
        return SurnameField.getText();
    }

    public String getName() {
        return NameField.getText();
    }

    public String getPatronimyc() {
        return PatronimycField.getText();
    }

    public String getBirth() {
        return BirthField.getText();
    }

    public String getPhone() {
        return PhoneField.getText();
    }
    
    public void SetEnabled() {
        PassportField.setEnabled(true);
        BirthField.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClientDialog dialog = new ClientDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BirthField;
    private javax.swing.JLabel DialogTitle;
    private javax.swing.JButton EditOK;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField PassportField;
    private javax.swing.JTextField PatronimycField;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
