package forms.dialogs;

import client.Stream;
import filters.FloatNumberFilter;
import forms.MainUserForm;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.PlainDocument;

public class DepositeDialog extends javax.swing.JDialog {

    ComboBoxModel currencyModel;
    
    public DepositeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
         try {
            setCurrencyModel("SELECT Мнемокод, Наименование FROM Валюта");
        } catch (IOException ex) {
            Logger.getLogger(MainUserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        PlainDocument doc = (PlainDocument) PercentField.getDocument();
        doc.setDocumentFilter(new FloatNumberFilter());
        doc = (PlainDocument) SumField.getDocument();
        doc.setDocumentFilter(new FloatNumberFilter());
    }
    
    public void setCurrencyModel(String executeStr) throws IOException {
        Vector currencies = new Vector();
        Stream server = new Stream();
        server.sendInt(5);
        server.sendString(executeStr);
        int count = Integer.parseInt(server.getString());
        for (int i = 0; i < count; i++) {
            String[] data = server.getString().split(":");
             currencies.add(data[0] + ":" + data[1]);
        }
         currencyModel = new DefaultComboBoxModel( currencies);
    }

    public void setDialogTitle(String title) {
        DialogTitle.setText(title);
    }

    public void setCode(int code) {
        CodeField.setText(Integer.toString(code));
    }

    public void setTitle(String deposite) {
        TitleField.setText(deposite);
    }

    public void setPercent(String percent) {
        PercentField.setText(percent);
    }

    public void setMinSum(String sum) {
        SumField.setText(sum);
    }
    
    public void setPartial(String partial) {
        if (partial.equals("Да")) {
            RadioButtonPartialYes.setSelected(true);
        }
        if (partial.equals("Нет")) {
            RadioButtonPartialNo.setSelected(true);
        }
    }
    
      public void setCurrency(String currency) {
        for (int i = 0; i < CurrencyCombo.getItemCount(); i++) {
            String[] mas = CurrencyCombo.getModel().getElementAt(i).split(":");
            if (mas[1].equals(currency)) {
                CurrencyCombo.setSelectedIndex(i);
            }
        }
    }

    public String getCode() {
        return CodeField.getText();
    }

    public String getTitle() {
        return TitleField.getText();
    }

    public String getPercent() {
        String percent = PercentField.getText().replace("%", "");
        return percent;
    }
    
    public String getMinSum() {
        return SumField.getText();
    }

    public String getPartial(){
        while (true) {
            if (RadioButtonPartialYes.isSelected()) {
                return "Да";
            }
            if (RadioButtonPartialNo.isSelected()) {
                return "Нет";
            } else {
                JOptionPane.showMessageDialog(null, "Не выбрано значение",
                        "Предупреждение", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    
     public String getCurrency() {
        String[] mas  = ((String)CurrencyCombo.getSelectedItem()).split(":");
        return mas[0];
    }

    public void SetEnabled() {

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DialogTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CodeField = new javax.swing.JTextField();
        TitleField = new javax.swing.JTextField();
        PercentField = new javax.swing.JTextField();
        SumField = new javax.swing.JTextField();
        RadioButtonPartialYes = new javax.swing.JRadioButton();
        RadioButtonPartialNo = new javax.swing.JRadioButton();
        EditOK = new javax.swing.JButton();
        CurrencyCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Депозит");

        DialogTitle.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        DialogTitle.setForeground(new java.awt.Color(0, 156, 190));
        DialogTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DialogTitle.setText("Редактировать");

        jLabel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("Код");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Наименование");

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Процентная ставка");

        jLabel4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Минимальная сумма");

        jLabel5.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Частичное снятие");

        jLabel6.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Валюта вклада");

        CodeField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        CodeField.setForeground(new java.awt.Color(30, 30, 30));
        CodeField.setDisabledTextColor(new java.awt.Color(50, 50, 50));
        CodeField.setEnabled(false);
        CodeField.setSelectionColor(new java.awt.Color(0, 156, 190));

        TitleField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        TitleField.setForeground(new java.awt.Color(30, 30, 30));
        TitleField.setSelectionColor(new java.awt.Color(0, 156, 190));

        PercentField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        PercentField.setForeground(new java.awt.Color(30, 30, 30));
        PercentField.setSelectionColor(new java.awt.Color(0, 156, 190));

        SumField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        SumField.setForeground(new java.awt.Color(30, 30, 30));
        SumField.setSelectionColor(new java.awt.Color(0, 156, 190));

        buttonGroup1.add(RadioButtonPartialYes);
        RadioButtonPartialYes.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        RadioButtonPartialYes.setForeground(new java.awt.Color(30, 30, 30));
        RadioButtonPartialYes.setText("Да");

        buttonGroup1.add(RadioButtonPartialNo);
        RadioButtonPartialNo.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        RadioButtonPartialNo.setForeground(new java.awt.Color(30, 30, 30));
        RadioButtonPartialNo.setSelected(true);
        RadioButtonPartialNo.setText("Нет");

        EditOK.setBackground(new java.awt.Color(0, 156, 190));
        EditOK.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        EditOK.setForeground(new java.awt.Color(255, 255, 255));
        EditOK.setText("ОК");
        EditOK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(15, 212, 255), new java.awt.Color(0, 175, 214), new java.awt.Color(0, 58, 71), new java.awt.Color(0, 112, 137)));
        EditOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditOKActionPerformed(evt);
            }
        });

        CurrencyCombo.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        CurrencyCombo.setForeground(new java.awt.Color(30, 30, 30));
        CurrencyCombo.setModel(currencyModel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DialogTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SumField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(TitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(CodeField)
                    .addComponent(PercentField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RadioButtonPartialYes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RadioButtonPartialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CurrencyCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(EditOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(DialogTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PercentField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SumField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonPartialYes)
                    .addComponent(RadioButtonPartialNo)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CurrencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(EditOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_EditOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DepositeDialog dialog = new DepositeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeField;
    private javax.swing.JComboBox<String> CurrencyCombo;
    private javax.swing.JLabel DialogTitle;
    private javax.swing.JButton EditOK;
    private javax.swing.JTextField PercentField;
    private javax.swing.JRadioButton RadioButtonPartialNo;
    private javax.swing.JRadioButton RadioButtonPartialYes;
    private javax.swing.JTextField SumField;
    private javax.swing.JTextField TitleField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
