package forms;

import forms.dialogs.FileNameDialog;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ReportForm extends javax.swing.JFrame {

    public ReportForm() {
        initComponents();
    }

    public void setTitle(String title) {
        ReportHeader.setText(title);
    }

    public void setText(String title) {
        ReportArea.setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportArea = new javax.swing.JTextArea();
        SaveReportButton = new javax.swing.JButton();
        ReportHeader = new javax.swing.JLabel();

        setTitle("Отчет");

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Отчет");

        ReportArea.setEditable(false);
        ReportArea.setBackground(new java.awt.Color(240, 240, 240));
        ReportArea.setColumns(20);
        ReportArea.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        ReportArea.setForeground(new java.awt.Color(30, 30, 30));
        ReportArea.setLineWrap(true);
        ReportArea.setRows(20);
        ReportArea.setTabSize(4);
        ReportArea.setWrapStyleWord(true);
        ReportArea.setBorder(null);
        ReportArea.setDisabledTextColor(new java.awt.Color(30, 30, 30));
        ReportArea.setEnabled(false);
        jScrollPane1.setViewportView(ReportArea);

        SaveReportButton.setBackground(new java.awt.Color(230, 230, 230));
        SaveReportButton.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        SaveReportButton.setForeground(new java.awt.Color(30, 30, 30));
        SaveReportButton.setText("Сохранить");
        SaveReportButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(230, 230, 230), new java.awt.Color(86, 86, 86), new java.awt.Color(147, 147, 147)));
        SaveReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveReportButtonActionPerformed(evt);
            }
        });

        ReportHeader.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        ReportHeader.setForeground(new java.awt.Color(30, 30, 30));
        ReportHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(SaveReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReportHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ReportHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SaveReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveReportButtonActionPerformed
        FileNameDialog dlg = new FileNameDialog(this, true);
        dlg.setLocationRelativeTo(null);
        dlg.setVisible(true);
        BufferedWriter writer;
        try {
            writer = new BufferedWriter(new FileWriter("Reports\\" + dlg.getFileName() + ".txt", true));
            writer.write("\t\tОтчет\n\n" + ReportHeader.getText() + "\n\n");
            writer.write(ReportArea.getText());
            writer.close();
            JOptionPane.showMessageDialog(null, "Новый отчет сохранен в файле " + dlg.getFileName() + ".txt",
                    "Отчет", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(MainUserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_SaveReportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ReportArea;
    private javax.swing.JLabel ReportHeader;
    private javax.swing.JButton SaveReportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
