package forms;

import client.Stream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

public class StatisticsForm extends javax.swing.JFrame {

    private DefaultListModel modelStatistics;

    public StatisticsForm() {
        try {
            setStatisticsModel("SELECT * FROM Статистика");
        } catch (IOException ex) {
            Logger.getLogger(MainUserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    public void setStatisticsModel(String executeStr) throws IOException {
        modelStatistics = new DefaultListModel();
        Stream server = new Stream();
        server.sendInt(17);
        server.sendString(executeStr);
        int count = server.getInt();
        for (int i = 0; i < count; i++) {
            modelStatistics.addElement(server.getString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListStatistics = new javax.swing.JList<>();
        DeleteButton = new javax.swing.JButton();
        DeleteAllButton = new javax.swing.JButton();
        ButtonStatisticsReport = new javax.swing.JButton();

        setTitle("История подключений");

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Статистика подключений");

        ListStatistics.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        ListStatistics.setForeground(new java.awt.Color(30, 30, 30));
        ListStatistics.setModel(modelStatistics);
        ListStatistics.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListStatistics.setSelectionBackground(new java.awt.Color(0, 156, 190));
        ListStatistics.setSelectionForeground(new java.awt.Color(254, 254, 254));
        ListStatistics.setVisibleRowCount(10);
        ListStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListStatisticsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListStatistics);

        DeleteButton.setBackground(new java.awt.Color(230, 230, 230));
        DeleteButton.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(30, 30, 30));
        DeleteButton.setText("Удалить");
        DeleteButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(230, 230, 230), new java.awt.Color(86, 86, 86), new java.awt.Color(147, 147, 147)));
        DeleteButton.setEnabled(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        DeleteAllButton.setBackground(new java.awt.Color(230, 230, 230));
        DeleteAllButton.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        DeleteAllButton.setForeground(new java.awt.Color(30, 30, 30));
        DeleteAllButton.setText("Удалить все");
        DeleteAllButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(230, 230, 230), new java.awt.Color(86, 86, 86), new java.awt.Color(147, 147, 147)));
        DeleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllButtonActionPerformed(evt);
            }
        });

        ButtonStatisticsReport.setBackground(new java.awt.Color(230, 230, 230));
        ButtonStatisticsReport.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        ButtonStatisticsReport.setForeground(new java.awt.Color(30, 30, 30));
        ButtonStatisticsReport.setText("Отчет");
        ButtonStatisticsReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(230, 230, 230), new java.awt.Color(86, 86, 86), new java.awt.Color(147, 147, 147)));
        ButtonStatisticsReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonStatisticsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStatisticsReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonStatisticsReport, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonStatisticsReport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ChangeTable() {
        getContentPane().removeAll();
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String selectedValue = ListStatistics.getSelectedValue();
        String code = selectedValue.substring(0, selectedValue.indexOf(" "));
        Stream server = new Stream();
        String executeStr = "DELETE FROM Статистика WHERE `Код`=" + code;
        server.sendInt(10);
        server.sendString(executeStr);
        
        try {
            setStatisticsModel("SELECT * FROM Статистика");
            ChangeTable();
        } catch (IOException ex) {
            Logger.getLogger(MainAdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void DeleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllButtonActionPerformed
        Stream server = new Stream();
        String executeStr = "DELETE FROM Статистика";
        server.sendInt(10);
        server.sendString(executeStr);
        
        try {
            setStatisticsModel("SELECT * FROM Статистика");
            ChangeTable();
        } catch (IOException ex) {
            Logger.getLogger(MainAdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteAllButtonActionPerformed

    private void ListStatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListStatisticsMouseClicked
        if (!ListStatistics.getSelectedValue().equals("")) {
            DeleteButton.setEnabled(true);
        } else {
            DeleteButton.setEnabled(false);
        }
    }//GEN-LAST:event_ListStatisticsMouseClicked

    private void ButtonStatisticsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStatisticsReportActionPerformed
        ReportForm dlg = new ReportForm();
        dlg.setLocationRelativeTo(null);
        dlg.setTitle("Статистика подключеий");
        String reportText = "Отчет составлен: " + new SimpleDateFormat("dd.MM.yyyy").format(new Date()) + "\n\n";
        for(int i =0;i<ListStatistics.getModel().getSize();i++){
            String fio = ListStatistics.getModel().getElementAt(i);
            reportText += "\t" + fio + "\n";
        }
        dlg.setText(reportText);
        dlg.setVisible(true);
    }//GEN-LAST:event_ButtonStatisticsReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonStatisticsReport;
    private javax.swing.JButton DeleteAllButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JList<String> ListStatistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
